export const FETCH_ALBUMS_BEGIN = 'FETCH_ALBUMS_BEGIN';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUMS_FAILURE = 'FETCH_ALBUMS_FAILURE';
export const CHANGE_SELECTED_ALBUM = 'CHANGE_SELECTED_ALBUM';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
